# Generated by Django 5.0.3 on 2024-03-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="remember_me",
            field=models.BooleanField(default=False),
        ),
    ]
